version: '3.8'

networks:
    go_gin-networks:
        external: true

services:
    go_gin-api:
        container_name: go_gin-api
        build: .
        volumes:
            - .:/go/src/
        ports:
            - 7001:7000
        networks:
            - go_gin-networks
    
    go_gin-postgres:
        container_name: go_gin-postgres
        restart: always
        image: postgres:13.2
        ports:
            - 5432:5432
        networks:
            - go_gin-networks
        environment:
            - POSTGRES_DB=gin
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=secret
            - TZ=GMT
        volumes:
            - "./data/postgres:/var/lib/postgresql/data"
