version: '3.8'

networks:
    go_gin-networks:
        external: true

services:
    go_gin-api:
        container_name: go_gin-api
        build: .
        volumes:
            - .:/go/src/
        ports:
            - 7001:7000
        networks:
            - go_gin-networks
    
    go_gin-postgres:
        container_name: go_gin-postgres
        restart: always
        image: postgres
        volumes:
            - .docker/dbdata:/var/lib/postgres
        ports:
            - 5432:5432
        networks:
            - go_gin-networks
        environment:
            - POSTGRES_PASSWORD=secret
