version: '3.3'

volumes:
  go-api-database:
    external: true

services:
  go-api-database:
    image: mysql:8
    volumes:
      - go-api-database:/var/lib/mysql
    ports:
      - "33069:3306"
    environment:
      - "MYSQL_DATABASE=${DB_DATABASE}"
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=true"
