version: '3.8'

volumes:
    go-api-exemple-3-db:
        external: true
    go-api-exemple-3-mongo:
        external: true

networks:
    go-api-exemple-3-networks:
        external: true

services:
    go-api-exemple-3-db:
        container_name: go-api-exemple-3-db
        image: mysql:5.7
        volumes:
            - go-api-exemple-3-db:/var/lib/mysql
        ports:
            - 33062:3306
        environment:
            - "MYSQL_ALLOW_EMPTY_PASSWORD=true"
            - "MYSQL_DATABASE=database"
            - "MYSQL_USER=user"
            - "MYSQL_PASSWORD=secret"
        networks:
            - go-api-exemple-3-networks
    
    go-api-exemple-3-mongo:
        container_name: go-api-exemple-3-mongo
        image: mongo:latest
        environment:
            - MONGO_DATA_DIR=/data/db
        volumes:
            - go-api-exemple-3-mongo:/data/db
        ports:
        - 27017:27017
        networks:
            - go-api-exemple-3-networks

    go-api-exemple-3-api:
        container_name: go-api-exemple-3-api
        build: ./docker/go
        volumes:
            - .:/go/src/
        ports:
            - ${API_PORT}:${API_PORT}
        depends_on:
            - "go-api-exemple-3-db"
        networks:
            - go-api-exemple-3-networks
